export default {
  albula: {
    labels: [
      {
        x: 701,
        y: 439,
        name: 'Bergün',
        type: 'place',
      },
      {
        x: 2837,
        y: 4544,
        name: 'Preda',
        type: 'place',
      },
      {
        x: 7887,
        y: 5375,
        name: 'Albulapass',
        type: 'place',
      },
      {
        x: 7914,
        y: 7706,
        name: 'Spinas',
        type: 'place',
      },
      {
        x: 4332,
        y: 2214,
        name: 'Alp da Tisch',
        type: 'place',
      },
      {
        x: 4979,
        y: 5557,
        name: 'Crap Alv',
        type: 'place',
      },
      {
        x: 7564,
        y: 6490,
        name: 'Piz da las Blais',
        type: 'peak',
      },
      {
        x: 7710,
        y: 3816,
        name: 'Piz Üertsch',
        type: 'peak',
      },
      {
        x: 3478,
        y: 3348,
        name: 'Piz Muot',
        type: 'peak',
      },
      {
        x: 4517,
        y: 978,
        name: 'Piz Darlux',
        type: 'peak',
      },
      {
        x: 6027,
        y: 1620,
        name: 'Tschimas da Tisch',
        type: 'peak',
      },
      {
        x: 2712,
        y: 7784,
        name: 'La Piramida',
        type: 'peak',
      },
    ],
  },
  furka: {
    labels: [
      {
        x: 2922,
        y: 7094,
        name: 'Oberwald',
        type: 'place',
      },
      {
        x: 3704,
        y: 4110,
        name: 'Gletsch',
        type: 'place',
      },
      {
        x: 1943,
        y: 4072,
        name: 'Grimselpass',
        type: 'place',
      },
      {
        x: 7838,
        y: 2815,
        name: 'Furkapass',
        type: 'place',
      },
      {
        x: 3860,
        y: 661,
        name: 'Vorder Gärstenhorn',
        type: 'peak',
      },
      {
        x: 6824,
        y: 5134,
        name: 'Tällistock',
        type: 'peak',
      },
      {
        x: 7158,
        y: 1355,
        name: 'Chli Furkahorn',
        type: 'peak',
      },
      {
        x: 3337,
        y: 1424,
        name: 'Hohhoren',
        type: 'peak',
      },
      {
        x: 7443,
        y: 6970,
        name: 'Vorder Berg',
        type: 'peak',
      },
      {
        x: 5704,
        y: 1141,
        name: 'Rhonegletscher',
        type: 'place',
      },
      {
        x: 724,
        y: 699,
        name: 'Älpersulz',
        type: 'place',
      },
      {
        x: 5719,
        y: 7656,
        name: 'Schärlichwang',
        type: 'place',
      },
      {
        x: 7092,
        y: 3442,
        name: 'Muttbach-Belvédère',
        type: 'place',
      },
    ],
  },
  saentis: {
    labels: [
      {
        x: 1173,
        y: 6280,
        name: 'Säntis',
        type: 'peak',
      },
      {
        x: 3339,
        y: 7321,
        name: 'Altmann',
        type: 'peak',
      },
      {
        x: 5981,
        y: 7645,
        name: 'Mutschen',
        type: 'peak',
      },
      {
        x: 4659,
        y: 3231,
        name: 'Schäfler',
        type: 'peak',
      },
      {
        x: 5611,
        y: 5825,
        name: 'Hundstein',
        type: 'peak',
      },
      {
        x: 2443,
        y: 4462,
        name: 'Öhrlikopf',
        type: 'peak',
      },
      {
        x: 4506,
        y: 5396,
        name: 'Meglisalp',
        type: 'place',
      },
      {
        x: 7329,
        y: 5744,
        name: 'Bollenwees',
        type: 'place',
      },
      {
        x: 5068,
        y: 4244,
        name: 'Seealp',
        type: 'place',
      },
      {
        x: 7476,
        y: 2183,
        name: 'Wasserauen',
        type: 'place',
      },
      {
        x: 6250,
        y: 2389,
        name: 'Ebenalp',
        type: 'place',
      },
      {
        x: 7206,
        y: 4332,
        name: 'Bogartenlücke',
        type: 'place',
      },
      {
        x: 3841,
        y: 7730,
        name: 'Zwinglipass',
        type: 'place',
      },
    ],
  },
  jungfrau: {
    labels: [
      {
        x: 348,
        y: 2268,
        name: 'Lauterbrunnen',
        type: 'place',
      },
      {
        x: 1075,
        y: 434,
        name: 'Wengen',
        type: 'place',
      },
      {
        x: 4029,
        y: 2752,
        name: 'Kleine Scheidegg',
        type: 'place',
      },
      {
        x: 5444,
        y: 6956,
        name: 'Jungfraujoch',
        type: 'place',
      },
      {
        x: 4192,
        y: 8119,
        name: 'Jungfrau',
        type: 'peak',
      },
      {
        x: 6834,
        y: 5683,
        name: 'Mönch',
        type: 'peak',
      },
      {
        x: 7434,
        y: 3557,
        name: 'Eiger',
        type: 'peak',
      },
      {
        x: 3027,
        y: 1951,
        name: 'Lauberhorn',
        type: 'peak',
      },
      {
        x: 3145,
        y: 1070,
        name: 'Tschuggen',
        type: 'peak',
      },
      {
        x: 2165,
        y: 3778,
        name: 'Wengernalp',
        type: 'place',
      },
      {
        x: 7567,
        y: 6104,
        name: 'Mönchsjoch',
        type: 'place',
      },
      {
        x: 7208,
        y: 1004,
        name: 'Alpligen',
        type: 'place',
      },
      {
        x: 5789,
        y: 3587,
        name: 'Rotstock',
        type: 'peak',
      },
      {
        x: 1249,
        y: 6368,
        name: 'Schwarzmönch',
        type: 'peak',
      },
      {
        x: 3144,
        y: 7541,
        name: 'Silberhorn',
        type: 'peak',
      },
      {
        x: 4122,
        y: 6725,
        name: 'Schneehoren',
        type: 'peak',
      },
      {
        x: 5476,
        y: 5388,
        name: 'Mönchplateau',
        type: 'peak',
      },
      {
        x: 285,
        y: 4408,
        name: 'Trümmelbach',
        type: 'place',
      },
      {
        x: 5925,
        y: 6911,
        name: 'Sphinx',
        type: 'peak',
      },
    ],
  },
  thurgau: {
    labels: [
      {
        x: 4629,
        y: 5271,
        name: 'Bischofszell',
        type: 'place',
      },
      {
        x: 5165,
        y: 4386,
        name: 'Sitterdorf',
        type: 'place',
      },
      {
        x: 6108,
        y: 2132,
        name: 'Zihlschlacht',
        type: 'place',
      },
      {
        x: 1659,
        y: 1787,
        name: 'Kradolf',
        type: 'place',
      },
      {
        x: 4998,
        y: 6324,
        name: 'Bischofsberg',
        type: 'peak',
      },
      {
        x: 5721,
        y: 6874,
        name: 'Hauptwil',
        type: 'place',
      },
      {
        x: 1872,
        y: 7971,
        name: 'Niederbüren',
        type: 'place',
      },
      {
        x: 3504,
        y: 3653,
        name: 'Hohentannen',
        type: 'place',
      },
      {
        x: 3256,
        y: 1406,
        name: 'Heldswil',
        type: 'place',
      },
      {
        x: 7400,
        y: 5338,
        name: 'Bärg',
        type: 'peak',
      },
      {
        x: 7325,
        y: 6226,
        name: 'Frohburg',
        type: 'peak',
      },
      {
        x: 2367,
        y: 4023,
        name: 'Halden',
        type: 'place',
      },
      {
        x: 4778,
        y: 3202,
        name: 'Felsenholz',
        type: 'peak',
      },
      {
        x: 7972,
        y: 5137,
        name: 'Wilen',
        type: 'place',
      },
      {
        x: 7354,
        y: 4294,
        name: 'Leutswil',
        type: 'place',
      },
      {
        x: 3341,
        y: 5565,
        name: 'Katzensteig',
        type: 'place',
      },
      {
        x: 789,
        y: 7278,
        name: 'Niederhelfenschwil',
        type: 'place',
      },
      {
        x: 503,
        y: 527,
        name: 'Sulgen',
        type: 'place',
      },
    ],
  },
};
