import {HIGHLIGHT_BRIDGE_COSTS, HIGHLIGHT_GROUND_COSTS, HIGHLIGHT_MIN_RADIUS_LIMITS} from '../cameras/highlightTypes.js';
import {ROUTE_TYPE_BRIDGE, ROUTE_TYPE_GROUND} from './routeTypes.js';
export const LIMIT_TYPE_MIN_RADIUS = 'minRadius';

export const LIMIT_TYPES = [LIMIT_TYPE_MIN_RADIUS];

export const LIMIT_TYPES_TO_HIGHLIGHTS = {
  [LIMIT_TYPE_MIN_RADIUS]: HIGHLIGHT_MIN_RADIUS_LIMITS,
  [ROUTE_TYPE_BRIDGE]: HIGHLIGHT_BRIDGE_COSTS,
  [ROUTE_TYPE_GROUND]: HIGHLIGHT_GROUND_COSTS
};

export const LIMIT_TYPES_TO_LABEL = {
  [LIMIT_TYPE_MIN_RADIUS]: 'RADIUS_LIMITS_LABEL'
};