import {
  HIGHLIGHT_MAX_GRADIENT_LIMIT,
  HIGHLIGHT_MAX_VARIANCE_LIMIT,
  HIGHLIGHT_MIN_GAP_LIMIT,
  HIGHLIGHT_MIN_RADIUS_LIMIT,
} from '../cameras/highlightTypes.js';

export const LIMIT_TYPE_MIN_RADIUS = 'minRadius';
export const LIMIT_TYPE_MAX_GRADIENT = 'maxGradient';
export const LIMIT_TYPE_MAX_VARIANCE = 'maxVariance';
export const LIMIT_TYPE_MIN_GAP = 'minGap';

export const LIMIT_TYPES = [
  LIMIT_TYPE_MIN_RADIUS,
  LIMIT_TYPE_MIN_GAP,
  LIMIT_TYPE_MAX_GRADIENT,
  LIMIT_TYPE_MAX_VARIANCE,
];

export const LIMIT_TYPES_TO_HIGHLIGHTS = {
  [LIMIT_TYPE_MIN_RADIUS]: HIGHLIGHT_MIN_RADIUS_LIMIT,
  [LIMIT_TYPE_MAX_GRADIENT]: HIGHLIGHT_MAX_GRADIENT_LIMIT,
  [LIMIT_TYPE_MAX_VARIANCE]: HIGHLIGHT_MAX_VARIANCE_LIMIT,
  [LIMIT_TYPE_MIN_GAP]: HIGHLIGHT_MIN_GAP_LIMIT,
};

export const LIMIT_TYPES_TO_LABEL = {
  [LIMIT_TYPE_MIN_RADIUS]: 'MIN_RADIUS_LIMIT_LABEL',
  [LIMIT_TYPE_MAX_GRADIENT]: 'MAX_GRADIENT_LIMIT_LABEL',
  [LIMIT_TYPE_MAX_VARIANCE]: 'MAX_VARIANCE_LIMIT_LABEL',
  [LIMIT_TYPE_MIN_GAP]: 'MIN_GAP_LIMIT_LABEL',
};
