import {HIGHLIGHT_MAX_GRADIENT_LIMITS, HIGHLIGHT_MIN_RADIUS_LIMITS} from '../cameras/highlightTypes.js';

export const LIMIT_TYPE_MIN_RADIUS = 'minRadius';
export const LIMIT_TYPE_MAX_GRADIENT = 'maxGradient';

export const LIMIT_TYPES = [LIMIT_TYPE_MIN_RADIUS, LIMIT_TYPE_MAX_GRADIENT];

export const LIMIT_TYPES_TO_HIGHLIGHTS = {
  [LIMIT_TYPE_MIN_RADIUS]: HIGHLIGHT_MIN_RADIUS_LIMITS,
  [LIMIT_TYPE_MAX_GRADIENT]: HIGHLIGHT_MAX_GRADIENT_LIMITS,
};

export const LIMIT_TYPES_TO_LABEL = {
  [LIMIT_TYPE_MIN_RADIUS]: 'MIN_RADIUS_LIMITS_LABEL',
  [LIMIT_TYPE_MAX_GRADIENT]: 'MAX_GRADIENT_LIMITS_LABEL'
};